In [1]:
import pandas as pd

In [136]:
train = pd.read_csv('/opt/ml/input/dialogue_data/train.csv',index_col=0)
valid = pd.read_csv('/opt/ml/input/dialogue_data/valid.csv',index_col=0)

In [137]:
train.keys()

Index(['id', 'media', 'date', 'category', 'subject', 'speaker_type',
       'raw_text', 'raw_lines', 'norm_texts', 'text_morphs', 'speech_Act',
       'speech_Cat', 'speech_CatDet'],
      dtype='object')

In [142]:
train.head(10)

,id,media,date,category,subject,speaker_type,raw_text,raw_lines,norm_texts,text_morphs,speech_Act,speech_Cat,speech_CatDet
0,132160,카카오톡,2021-11-03,일상대화,교통,다자간 대화,1 : 버스타고 기분 좋았던 경험?\n2 : 나는 버스타고 정처없이 떠돌 때 기분 ...,"[{'id': 1, 'text': '1 : 버스타고 기분 좋았던 경험?', 'nor...","['버스타고 기분 좋았던 경험?', '나는 버스타고 정처없이 떠돌 때 기분 좋더라'...",['버스/NNG+타/VV+고/EC+기분/NNG+좋/VA+았/EP+던/ETM+경험/N...,"['(지시) 질문하기', '(표현) 긍정감정 표현하기', '(표현) 긍정감정 표현하...","[2, 4, 4, 1, 1, 4, 2, 1, 2, 4, 2, 4]","[23, 42, 42, 13, 12, 42, 23, 11, 23, 42, 23, 43]"
1,46838,카카오톡,2021-10-06,일상대화,미용,1:1,1 : 요즘 모공관리가 고민이야.\n1 : 모공관리하는 너만의 비법이 있니?\n2 ...,"[{'id': 1, 'text': '1 : 요즘 모공관리가 고민이야.', 'norm...","['요즘 모공관리가 고민이야.', '모공관리하는 너만의 비법이 있니?', '나는 가...",['요즘/NNG+모공/NNG+관리/NNG+가/JKS+고민/NNG+이/VCP+야/EF...,"['(단언) 주장하기', '(지시) 질문하기', '(단언) 진술하기', '(단언) ...","[1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[12, 23, 13, 13, 12, 13, 13, 13, 13, 13, 12, 1..."
2,133919,카카오톡,2021-11-03,일상대화,미용,다자간 대화,1 : 피부에 젤 중요한 건 선크림이다!\n2 : 맞아 키키 선크림 매일 바르고 다...,"[{'id': 1, 'text': '1 : 피부에 젤 중요한 건 선크림이다!', '...","['피부에 젤 중요한 건 선크림이다!', '맞아 키키 선크림 매일 바르고 다니지',...",['피부/NNG+에/JKB+젤/MAG+중요/NNG+한/XSA+ETM+건/NNB+JX...,"['(단언) 진술하기', '(단언) 진술하기', '(단언) 진술하기', '(단언) ...","[1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, ...","[13, 13, 13, 12, 13, 12, 13, 13, 23, 12, 12, 2..."
3,90019,카카오톡,2021-10-25,일상대화,교통,1:1,1 : 회사랑은 위치 가깝나 ?\n2 : 차 타고 30분 정도?\n1 : 아 꽤 거...,"[{'id': 1, 'text': '1 : 회사랑은 위치 가깝나 ?', 'norm_...","['회사랑은 위치 가깝나 ?', '차 타고 30분 정도?', '아 꽤 거리가 있는 ...","['회사/NNG+랑/JKB+은/JX+위치/NNG+가깝/VA+나/EF', '차/NNG...","['(지시) 질문하기', '(단언) 주장하기', '(단언) 진술하기', '(단언) ...","[2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, ...","[23, 12, 13, 12, 12, 12, 12, 23, 12, 12, 12, 1..."
4,81331,카카오톡,2021-10-20,일상대화,미용,1:1,1 : 요즘 미장원에 손님들이 많아요?\n2 : 코로나 초창기에는 얼마 없었는데 요...,"[{'id': 1, 'text': '1 : 요즘 미장원에 손님들이 많아요?', 'n...","['요즘 미장원에 손님들이 많아요?', '코로나 초창기에는 얼마 없었는데 요즘엔 많...",['요즘/NNG+미장원/NNG+에/JKB+손님/NNG+들/XSN+이/JKS+많/VA...,"['(지시) 질문하기', '(단언) 진술하기', '(단언) 주장하기', '(단언) ...","[2, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[23, 13, 12, 12, 12, 12, 12, 13, 13, 12]"
5,88203,페이스북,2021-10-25,일상대화,스포츠/레저,1:1,1 : 배구 쌍둥이 그리스 갔데?\n2 : 그리스에서 잘하고있는가?\n1 : 어제갔...,"[{'id': 1, 'text': '1 : 배구 쌍둥이 그리스 갔데?', 'norm...","['배구 쌍둥이 그리스 갔데?', '그리스에서 잘하고 있는가?', '어제갔다 키키 ...","['배구/NNG+쌍둥이/NNG+그리스/NNP+갔/VV+EP+데/EF', '그리스/N...","['(지시) 질문하기', '(지시) 질문하기', '(단언) 진술하기', '(단언) ...","[2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1]","[23, 23, 13, 12, 13, 12, 13, 23, 13, 13, 12]"
6,67601,카카오톡,2021-10-14,일상대화,가족,1:1,1 : 언니 결혼식 와준 거 땡큐야\n1 : 사진 나왔대서 인터넷으로 보내준댔는데 ...,"[{'id': 1, 'text': '1 : 언니 결혼식 와준 거 땡큐야', 'nor...","['언니 결혼식 와준 거 땡큐야', '사진 나왔대서 인터넷으로 보내준댔는데 내 친구...","['언니/NNG+결혼식/NNG+와/JC+준거/NNG+땡큐/IC+야/IC', '사진/...","['(표현) 감사하기', '(단언) 진술하기', '(단언) 주장하기', '(단언) ...","[4, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, ...","[40, 13, 12, 12, 13, 12, 23, 12, 12, 12, 23, 2..."
7,79362,카카오톡,2021-10-20,일상대화,군대,1:1,1 : 너 아들 군대 가려면 멀었잖아\n2 : 한 20년은 지나야지? 키키\n1 :...,"[{'id': 1, 'text': '1 : 너 아들 군대 가려면 멀었잖아', 'no...","['너 아들 군대 가려면 멀었잖아', '한 20년은 지나야지? 키키', '그때는 지...",['너/NP+아들/NNG+군대/NNG+가/VV+려면/EC+멀/VA+었잖/EC+VX+...,"['(단언) 진술하기', '(지시) 질문하기', '(지시) 질문하기', '(단언) ...","[1, 2, 2, 1, 1, 1, 1, 1, 1, 1]","[13, 23, 23, 12, 13, 13, 12, 12, 12, 12]"
8,60549,카카오톡,2021-10-08,일상대화,식음료,1:1,1 : 점심먹었어?\n2 : 응 수제비먹었어\n2 : 너도 점심 먹었어?\n1 : ...,"[{'id': 1, 'text': '1 : 점심먹었어?', 'norm_text': ...","['점심먹었어?', '응 수제비먹었어', '너도 점심 먹었어?', '응응 난 게살샐...","['점심/NNG+먹/VV+었/EP+어/EF', '응/IC+수제비/NNG+먹/VV+었...","['(지시) 질문하기', '(단언) 진술하기', '(지시) 질문하기', '(단언) ...","[2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1]","[23, 13, 23, 13, 24, 13, 24, 21, 23, 13, 12, 1..."
9,166110,카카오톡,2021-11-12,일상대화,방송/연예,1:1,1 : 노제 왤케 이쁨?\n2 : 노제 진짜 존예 키키\n1 : 웬만한 연예인보다 ...,"[{'id': 1, 'text': '1 : 노제 왤케 이쁨?', 'norm_text...","['노제 왤케 이쁨?', '노제 진짜 존예 키키', '웬만한 연예인보다 이쁜 듯 키...","['노제왤케이쁨/UNKNOWN', '노제진짜존예키키/UNKNOWN', '웬만/XR+...","['(지시) 질문하기', '(단언) 주장하기', '(단언) 주장하기', '(단언) ...","[2, 1, 1, 1, 1, 1, 1, 1, 3, 3, 2, 3, 1, 3, 2]","[23, 12, 12, 12, 12, 12, 12, 12, 32, 32, 21, 3..."

In [150]:
import random as random

In [162]:
r= random.randint(0,len(train))
r

25770

In [163]:
train.iloc[r,]['norm_texts']

"['머릿결이 건강한 편인가요?', '아니요 엄청 가늘어요', '저는 염색, 파마를 안하니 건강한 듯 싶은데요...', '머리도 굵은가요?', '남편은 탈모가 좀 진행되어서 오늘 머리에 바르는 약을 추가로 샀어요.', '아 많이 심각하신가봐요', '머리카락은 좀 가는 편인 듯 싶은데요... 매우 가늘지는 않음요.', '머리숱 많으세요?', '남자 탈모는 유전이라... 뭐 어쩔 수 없는 부분이 있죠. ;', '저는 머리숱이 적당한 편인 듯 싶어요', '저는 대머리 걱정될 정도', '거울은 자주 보세요? 하하', '하루종일 안 봐요']"

In [164]:
train.iloc[r,]['speech_Act']

"['(지시) 질문하기', '(단언) 진술하기', '(단언) 주장하기', '(지시) 질문하기', '(단언) 진술하기', '(단언) 주장하기', '(단언) 진술하기', '(지시) 질문하기', '(단언) 주장하기', '(단언) 주장하기', '(단언) 진술하기', '(지시) 질문하기', '(단언) 진술하기']"

In [165]:
train.iloc[r,]['speech_CatDet']

'[23, 13, 12, 23, 13, 12, 13, 23, 12, 12, 13, 23, 13]'

In [31]:
speech_unique = set()
for idx, row in train.iterrows():
    speech_unique.add(eval(row['speech_Act'])[0])
speech_unique

{'(단언) 반박하기',
 '(단언) 주장하기',
 '(단언) 진술하기',
 '(선언/위임하기)',
 '(언약) 거절하기',
 '(언약) 약속하기(제3자와)/(개인적 수준)',
 '(지시) 명령/요구하기',
 '(지시) 부탁하기',
 '(지시) 질문하기',
 '(지시) 충고/제안하기',
 '(표현) 감사하기',
 '(표현) 긍정감정 표현하기',
 '(표현) 부정감정 표현하기',
 '(표현) 사과하기',
 '(표현) 인사하기',
 'N/A',
 '턴토크 사인(관습적 반응)'}

In [96]:
# 전체 발화를 기준으로 describe
pd.DataFrame(train['raw_text'].apply(lambda x: len(x)).describe())

           raw_text
count  87689.000000
mean     397.036698
std      165.424663
min        3.000000
25%      278.000000
50%      369.000000
75%      471.000000
max     2602.000000

In [98]:
# 가장 긴 발화 기준으로 describe
pd.DataFrame(train['raw_text'].apply(lambda x: len(sorted(x.split('\n'),key=len,reverse=True)[0].split(':')[-1]))).describe().rename(columns={'raw_text':'max'})

                max
count  87689.000000
mean      35.055959
std       12.229101
min        0.000000
25%       26.000000
50%       33.000000
75%       41.000000
max      194.000000

In [99]:
# 평균 길이의 발화 기준으로 describe
text_list = train['raw_text'].apply(lambda x : sorted(x.split('\n'),key=len,reverse=True))
text_len = train['raw_text'].apply(lambda x : len(x.split('\n'))//2)
mean_texts = []
for t, l in zip(text_list, text_len):
    mean_texts.append(len(t[l].split(':')[-1]))
pd.DataFrame(mean_texts).describe().rename(columns={0:'mean'})

               mean
count  87689.000000
mean      19.270251
std        5.142382
min        0.000000
25%       16.000000
50%       18.000000
75%       22.000000
max       72.000000

In [100]:
# 가장 짧은 발화 기준으로 describe
pd.DataFrame(train['raw_text'].apply(lambda x: len(sorted(x.split('\n'),key=len,reverse=False)[0].split(':')[-1]))).describe().rename(columns={'raw_text':'min'})

                min
count  87689.000000
mean       9.642110
std        4.448039
min        0.000000
25%        6.000000
50%       10.000000
75%       13.000000
max       41.000000

In [110]:
sorted(train['raw_text'],key=len,reverse=False)[:10]

['2 :',
 '3 : 습하니까 더 그래',
 '1 : 저녁시간이 또 왔다',
 '2 : 내가 그 쥐약아니겠나 휴',
 '2 : 알겠어 해보고 후기를 알려줄께',
 '2 : 알겠어 하자마자 사진찍어서 보내줘',
 '1 : 중국 전력난이 심각한 수준이라 하네',
 '1 : 목 치료 받은 거 좀 괜찮다가 지금 좀 아프네',
 '1 : 요즘 해외를 못나가서 그런지 비행기값이 저렴하더라',
 '1 : 주말에 가족들이랑 바다 보러가는데 벌써부터 설렌다!']

In [108]:
sorted(train['raw_text'],key=len,reverse=False)[0]

'2 :'

In [112]:
sorted(train['raw_text'],key=len,reverse=False)[100]

'1 : 군대하면 생가나는건 뭐에요?\n2 :  친구들이요\n1 : 친구들이 직업군이라고 했죠?\n2 : 네 맞아요\n1 : 다 전역했어요?\n2 : 아뇨 근무중인친구도 있어요\n1 : 몇 명 근무중이에요?\n2 : 5명이요\n1 : 다 장교에요?\n2 : 아뇨 장교 3 부사관2이요'

In [129]:
total_list = train['subject'].unique().tolist()
total_list

['교통',
 '미용',
 '스포츠/레저',
 '가족',
 '군대',
 '식음료',
 '방송/연예',
 '회사/아르바이트',
 '반려동물',
 '게임',
 '영화/만화',
 '타 국가 이슈',
 '연애/결혼',
 '건강',
 '상거래 전반',
 '사회이슈',
 '교육',
 '계절/날씨',
 '여행',
 '주거와 생활',
 '상거래전반']

In [138]:
subject_utter=[]
for t in total_list:
    utterance=[]
    cat = []
    for i,r in train[(train['subject']==t) &  (train['speaker_type'] == '다자간 대화')].iterrows():
        utterance += eval(r['norm_texts'])
        cat += eval(r['speech_CatDet']) 
    subject_utter.append([t,utterance,cat])

In [140]:
pd.DataFrame(subject_utter,columns=['subject','text','catdet'])

,subject,text,catdet
0,교통,"[버스타고 기분 좋았던 경험?, 나는 버스타고 정처없이 떠돌 때 기분 좋더라, 사람...","[23, 42, 42, 13, 12, 42, 23, 11, 23, 42, 23, 4..."
1,미용,"[피부에 젤 중요한 건 선크림이다!, 맞아 키키 선크림 매일 바르고 다니지, 선크림...","[13, 13, 13, 12, 13, 12, 13, 13, 23, 12, 12, 2..."
2,스포츠/레저,"[오늘 낚시 간닷!, 어디로 가냐!, 뭐 잡냐, 헐 부럽다!, 바다 낚시 가는 거야...","[13, 23, 23, 12, 23, 12, 23, 12, 12, 12, 23, 2..."
3,가족,"[가족은 생각만 해도 든든해, 응? 키키 그치, 가족이 든든하징, 키키 맞지 맞지,...","[12, 12, 12, 12, 12, 12, 12, 12, 12, 23, 12, 1..."
4,군대,"[군대에서 시간을 헛투로 쓰지 않고 업그레이드 할 수 있는 방법이 있습니다., 어떤...","[13, 23, 23, 13, 23, 12, 13, 12, 12, 12, 13, 1..."
5,식음료,"[바닐라 라떼 좋아해?, 먹어 봤어?, 나는 바닐라 라떼는 안 먹어 키키, 커피는 ...","[23, 23, 12, 12, 12, 13, 23, 12, 13, 12, 12, 1..."
6,방송/연예,"[맞아요 여성용 유산균 먹어야 해요, 방송에서도 많이 나오더라구요!, 여자 연예인들...","[12, 12, 12, 12, 23, 12, 12, 12, 12, 12, 12, 1..."
7,회사/아르바이트,"[나중에 어떤 회사 다니고 싶어?, 나는 서울에 있는 회사 다니고싶어, 나는 출퇴근...","[23, 12, 12, 23, 12, 13, 13, 13, 23, 12, 12, 1..."
8,반려동물,"[친정에 놔두고 온 햄스터 보고싶다, 헉 너 햄스터 키웠어?, 햄스터 계속 키우던데...","[13, 23, 13, 42, 23, 13, 13, 23, 13, 13, 13, 2..."
9,게임,"[남편 플스 하는 중?, 오 어찌 암 개소름, 플스도 집에 있음? 키키, 요새도 즐...","[23, 12, 13, 23, 13, 12, 13, 12, 13, 12, 13, 1..."
10,영화/만화,"[듄 보고 싶었는데..., 김선호 영화도 찍는다던데 이름 뭐임, 키키 그래 난 그거...","[12, 23, 12, 12, 13, 12, 23, 12, 12, 23, 12, 1..."
11,타 국가 이슈,"[스위스가 동성 결혼 허용 했다네...?, 헐 키키 근데 나도 뭐 이제는 찬성, 오...","[12, 12, 13, 13, 12, 23, 13, 13, 13, 13, 12, 1..."
12,연애/결혼,"[이번에 내 동생 파혼했어., 저런 어쩌다 파혼했어?, 헉 얼마나 만났었는데?, 그...","[13, 23, 23, 13, 12, 12, 13, 23, 23, 13, 12, 1..."
13,건강,"[내 친구 탈모로 엄청 걱정하고 있어 ㅠㅠ, 헉 벌써 탈모라고?, 얼마나 빠졌어, ...","[12, 23, 23, 23, 12, 12, 12, 12, 12, 12, 12, 2..."
14,상거래 전반,"[인터넷 쇼핑몰에 달고나 만들기 다 품절이래 ㅠ, 헉 나도 그거 사려했는데 벌써?,...","[12, 23, 23, 12, 12, 13, 12, 13, 12, 12, 13, 1..."
15,사회이슈,"[다들 투자 해봤어?, 나는 해봤어., 나도야!, 투자를 하면 무조건 성공해?, 아...","[23, 13, 13, 23, 43, 13, 23, 42, 43, 13, 13, 2..."
16,교육,"[너는 대학교 다니고 있어?, 나는 대학 안 다니고 시험 준비!, 아니 나도 대학 ...","[23, 13, 13, 23, 13, 23, 23, 13, 12, 23, 13, 1..."
17,계절/날씨,"[난 겨울이 제일 싫어 키키, 나도 추위 많이 타서 겨울 싫어해 ㅠㅠ, 나는 차라리...","[12, 12, 12, 23, 12, 12, 13, 12, 12, 12, 12, 2..."
18,여행,"[나 요새 고민이 있어 ~, 뭔데? 고민을 말해봐, 그래 말해봐 들어줄게, 시부모님...","[13, 24, 24, 13, 23, 23, 12, 23, 13, 13, 24, 1..."
19,주거와 생활,"[집 주변에 병원이나 마트가 있어?, 옛날 집에는 있었는데 지금은 없어, 차타고 5...","[23, 13, 13, 12, 13, 12, 13, 12, 12, 23, 12, 1..."
20,상거래전반,"[얘들아 요즘 비트코인이 엄청 대센거 같더라, 너네도 코인하니?, 나는 안해 나는 ...","[12, 23, 13, 12, 12, 12, 12, 13, 43, 42, 13, 2..."

In [ ]:
train